/** @type {import('prettier').Config} */
module.exports = {
  // endOfLine: "lf",
  trailingComma: "none",
  semi: false,
  singleQuote: true,
  printWidth: 120,
  tabWidth: 2,
  bracketSpacing: true,
  // importOrder: [
  //   "^(react/(.*)$)|^(react$)",
  //   "^(next/(.*)$)|^(next$)",
  //   "<THIRD_PARTY_MODULES>",
  //   "",
  //   "^types$",
  //   "^@/types/(.*)$",
  //   "^@/config/(.*)$",
  //   "^@/lib/(.*)$",
  //   "^@/hooks/(.*)$",
  //   "^@/components/ui/(.*)$",
  //   "^@/components/(.*)$",
  //   "^@/styles/(.*)$",
  //   "^@/app/(.*)$",
  //   "",
  //   "^[./]",
  // ],
  // importOrderSeparation: false,
  // importOrderSortSpecifiers: true,
  // importOrderBuiltinModulesToTop: true,
  // importOrderParserPlugins: ["typescript", "jsx", "decorators-legacy"],
  // importOrderMergeDuplicateImports: true,
  // importOrderCombineTypeAndValueImports: true,
  // plugins: ["@ianvs/prettier-plugin-sort-imports"],
};
